wwcodeapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "wwcodeapp"

urlpatterns = [
    path('index/',views.index, name='index'),
    path('details/',views.details, name='details'),
    path('cards/',views.cards, name='cards'),
    path('cards/id=<int:id>',views.cards, name='cards'),
    path('datas/',views.datas, name='datas'),
]

wwcodeproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wwcodeapp.urls')),
]

wwcodeapp/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    Question = models.CharField(max_length=350)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.Question

class Answertable(models.Model):
    Answer = models.CharField(max_length=350)
    #topicid = models.ForeignKey(Topic,default=1,on_delete=models.set_default)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.Answer

wwcodeapp/views.py
from django.shortcuts import render,redirect
import os
import openpyxl
from openpyxl import Workbook
from openpyxl import load_workbook
from pathlib import Path
import pandas as pd
from .models import Topic,Answertable
# Create your views here.
from django.http import HttpResponse,request

def index(request):
    #return HttpResponse('<h1>Home Page</h1>')
    return render(request,'wwcodeapp/index.html')

def details(request):
    return render(request,'wwcodeapp/details.html')

def datas(request):
    if request.method == "GET":
        return render(request,'wwcodeapp/datas.html')
    else:
        excel_file = request.FILES["excel_file"]
        
        #print(excel_file)
        currentdir = os.path.dirname(os.path.abspath(__file__))
        path = os.path.join(currentdir,"trial.xlsx")
        #print(path)
        xlsx_file = Path(currentdir, 'trial.xlsx')
        wb_obj = openpyxl.load_workbook(xlsx_file)
        sheet = wb_obj.active
        excel_data = {}
        i=1
        row_count = sheet.max_row
        column_count = sheet.max_column
        for i in range(2, row_count + 1):
            new_list = []
            for j in range(1, column_count + 1):
                data = sheet.cell(row=i, column=j).value
                #print(data, end='   ')
                new_list.append(data)
            #print('\n')
            excel_data[i]=new_list

        # iterating over the rows and
        # getting value from each cell in row
        #print(excel_data)
        #print("====")
        return render(request,'wwcodeapp/datas.html',{"excel_data":excel_data})

def cards_save(request,id):
    
    return redirect('cards')

def cards(request,**kwargs): 
    for key, value in kwargs.items (): 
        print ("%s == %s" %(key, value))
        if value:
            temp=value
        temp="id"+str(value)
        print(temp)
        #keys=form.cleaned_data[key]
        #print(keys)
    #if request.method == "GET":
        answer=request.GET[temp]
        print(answer)
        reg=Answertable(Answer = answer)
        reg.save()
    all_objects= Topic.objects.all()   
    qbank = [{ blog.pk: blog.Question} for blog in all_objects]
    #print(qbank)
  
    return render(request,'wwcodeapp/cards.html',{"qbank":qbank})

wwcodeapp/templates/wwcodeapp/cards.html
{% extends 'wwcodeapp/details.html' %}
{% block content %}

<div class="container is-widescreen" >
  <table class="table">
    <tr>

{% for i in qbank %}
    {% if forloop.counter0|divisibleby:4 %}
     <tr>
    {% endif %}
  {% for key,value in i.items %} 
  <td>
  <section class="card">
        <div class="card-inner">
            <article class="card-front">
                {{value}}
            </article>
            <article class="card-back">
              <br>
              <form action="/cards/id={{key}}" method="GET">
                {% csrf_token %}
              <div class="is-centered">
              <textarea class="textarea is-hovered" name="id{{key}}" id="id{{key}}" placeholder=""></textarea>
              <br>
              
              <div class="field is-grouped">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <p class="control">
                  <button type="submit" class="button is-link">
                    Save
                  </button>
                </p>
                <p class="control">
                  <button class="button is-danger">
                    Cancel
                  </button>
                </p>
                
              </div>
            </div> 
          </form>              
            </article>
        </div>      
  </section>
</td>

  {% endfor %}
{% endfor %}

</tr>
</table>
</div>

{% endblock content %}
 

wwcodeapp/templates/wwcodeapp/datas.html
{% extends 'wwcodeapp/index.html' %}
{% block content %}
<form name = "form" enctype = "multipart/form-data" 
         action = "{% url 'wwcodeapp:datas' %}" method = "POST" >
         {% csrf_token %}
         
         <br>
         
         
         <div class="container" style = "max-width:900px;">
            <center> 
                  <input type="file"
                  title="Upload excel file"
                  name="excel_file"
                  style="border: 1px solid black; padding: 5px;"
                  required="required">
                  <button style = "border:0px;background-color:#4285F4; margin-top:8%; 
                  height:35px; width:20%; margin-left:19%;" type = "submit" value = "Login" >
                  <strong>upload</strong>
               </button>
               
            </center>
			
         
      </form>
      {% if excel_data %}
      <br>
      <table class="  table is-bordered is-striped is-narrow is-hoverable is-fullwidth  ">
         <thead>
           <tr>
              <th>
                  ID
              </th>
              <th>
                 QUESTION
               </th>
           </tr>
         </thead>
         <tbody>  
            {% for key,value in excel_data.items %}
               <tr>
                  {% for j in value %}
                     <td>{{j}}</td>
                  {% endfor %}
               </tr>
            {% endfor %}
            </tbody>
          </table>
          {% endif %}
         </div>

{% endblock content %}

wwcodeapp/templates/wwcodeapp/details.html
{% extends 'wwcodeapp/index.html' %}
{% block content %}
<div class="container">


    
  <div class="field">
    <label class="label">QUESTION:</label>
    <div class="control">
        <textarea class="textarea" name="ques" id="ques" placeholder="e.g. Hello world"></textarea>
    </div>
  </div>
  <div class="field">
    <label class="label">ANSWER:</label>
    <div class="control">
        <textarea class="textarea" name="ans" id="ans" placeholder="e.g. Hello world"></textarea>
    </div>
  </div>
  
  <div class="field is-grouped">
    <div class="control">
      <button class="button is-link">Submit</button>
    </div>
    <div class="control">
      <button class="button is-link is-light">Cancel</button>
    </div>
  </div>

  <!--<div class="field">
    <label class="label">Username</label>
    <div class="control has-icons-left has-icons-right">
      <input class="input is-success" type="text" placeholder="Text input" value="bulma">
      <span class="icon is-small is-left">
        <i class="fas fa-user"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-check"></i>
      </span>
    </div>
    <p class="help is-success">This username is available</p>
  </div>
  
  <div class="field">
    <label class="label">Email</label>
    <div class="control has-icons-left has-icons-right">
      <input class="input is-danger" type="email" placeholder="Email input" value="hello@">
      <span class="icon is-small is-left">
        <i class="fas fa-envelope"></i>
      </span>
      <span class="icon is-small is-right">
        <i class="fas fa-exclamation-triangle"></i>
      </span>
    </div>
    <p class="help is-danger">This email is invalid</p>
  </div>
  
  <div class="field">
    <label class="label">Subject</label>
    <div class="control">
      <div class="select">
        <select>
          <option>Select dropdown</option>
          <option>With options</option>
        </select>
      </div>
    </div>
  </div>
  
  <div class="field">
    <label class="label">Message</label>
    <div class="control">
      <textarea class="textarea" placeholder="Textarea"></textarea>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <label class="checkbox">
        <input type="checkbox">
        I agree to the <a href="#">terms and conditions</a>
      </label>
    </div>
  </div>
  
  <div class="field">
    <div class="control">
      <label class="radio">
        <input type="radio" name="question">
        Yes
      </label>
      <label class="radio">
        <input type="radio" name="question">
        No
      </label>
    </div>
  </div>
  
  <div class="field is-grouped">
    <div class="control">
      <button class="button is-link">Submit</button>
    </div>
    <div class="control">
      <button class="button is-link is-light">Cancel</button>
    </div>
  </div>-->
</div>
    
{% endblock content %}

wwcodeapp/templates/wwcodeapp/index.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PYTHON WORLD</title>
    <link rel="stylesheet" href="{% static 'wwcodeapp/css/bulma.min.css' %}">
    <link rel="stylesheet" href="{% static 'wwcodeapp/css/card.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
  </head>
  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <img src="{% static 'wwcodeapp/img/globe.jpg' %}" width="112" height="28">
            <p class="navbar-item">FOR LEARNING</p>
            
      
          <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
          </a>
        </div>
      
        <div id="navbarBasicExample" class="navbar-menu">
          <div class="navbar-start">
            <a class="navbar-item" href="{% url 'wwcodeapp:index' %}">
             <span class="material-icons">
              home
             </span>
              Home
            </a>
            <a href="{% url 'wwcodeapp:cards' %}" class="navbar-item">
                <span class="material-icons">
                    question_answer
                </span>Q/A
            </a>
      
           <!--  <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link">
                More
              </a>-->
      
             <!-- <div class="navbar-dropdown">-->
                <a href="{% url 'wwcodeapp:details' %}" class="navbar-item">
                    <span class="material-icons">
                        add
                        </span>
                  ADD
                </a>
                <a class="navbar-item">
                 <img src="{% static 'wwcodeapp/img/job.png' %}">
                  Jobs
                </a>
                <a class="navbar-item">
                  <span class="material-icons">
                    contact_page
                    </span>
                  Contact
                </a>
                <hr class="navbar-divider">
                <div class="navbar-item has-dropdown is-hoverable">
                  <a class="navbar-link is-arrowless">
                    <span class="material-icons">
                      link
                      </span>
                    Links
                  </a>
                  <div class="navbar-dropdown">
                    <a href="{% url 'wwcodeapp:datas' %}" class="navbar-item">
                      <span class="material-icons">
                        import_export
                        </span>
                      IMPORT / EXPORT
                    </a>
                  </div>
                </div>
              <!--</div>
            </div>-->
          </div>
      
          
        </div>
        
      </nav>
      
      <div class="container is-max-widescreen">
        <div class="notification is-primary">
          <center>PYTHON WORLD !- A BLOG FOR KNOWLEDGE EXCHANGE</center>
        </div>
      </div>
      {% block content %}    
        <div class="container">
          <div class="columns is-desktop">
            <div class="column">
              <p class="title">
                <img class="is-background" src="{% static 'wwcodeapp/img/mainbg.jpeg' %}" alt="" width="640" height="310" />
                 
              </p>
            </div>
            <div class="column">
                         <br>Knowledge sharing is the act of exchanging information or understanding between individuals, teams, communities, or organizations. Knowledge may be explicit (meaning procedures and documents) or tacit (meaning intuitive and experience-based). Sharing knowledge is an intentional process that not only bolsters an individual's understanding but helps create or enhance an archive of accessible knowledge for others.

              The concept of knowledge sharing is important because it helps individuals and businesses be more agile and adaptable in the face of change and helps ensure continued growth and survival. </div>
          
            </div>
            
        </div>
      {% endblock content %}

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        EDIT FOOTER LATER</p>
    </div>
  </footer>
  </body>
</html>